name: Node Js

on: [push]

jobs:
  Node-Js: 
      runs-on: windows-latest

      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install 
      - run: npm ci
      - run: dir "frontend\\public\\index.html"
      - run: if exist "frontend\public\index.html" (npm run build)
      - run: npm test
      - run: node C:\\Users\\asyas\\hungry-cat\\backend\\server.js